### PR TITLE
Solve the problem of insufficient width of Y-axis label display

### PR DESCRIPTION
**Pull request by weilanxiao**

### CODE REVIEW

**Comment by hannesa2** [comment]
Some screenshot tests are failing, but maybe it's ok, because you changed something.
The annoying thing is, that you have to download diff files in pull request summary, for investigation.

To avoid this, I made https://github.com/AppDevNext/AndroidChart/pull/213 here you see diff immediate in pull request as comment.

@weilanxiao Please rebase this pull request to recent master, then we can see diffs immediate

**Comment by weilanxiao** [comment]
Hello, I created a new branch based on the latest `master` where the commit is `12fa970f`, and then picked the original commits to the new branch. Finally, I forcefully pushed to `fix_y_label_width`. Is this operation correct?

**Comment by hannesa2** [comment]
The new branch was an extra unneeded task, but the result if fine
The easiest way to rebase would be:
```
git fetch upstream
git checkout fix_y_label_width
git rebase upstream/master
git push -f
```

**Comment by hannesa2** [comment]
Now I started the CI pipeline and I expect failing screenshot test, because I already tested this branch concerning screenshot tests https://github.com/AppDevNext/AndroidChart/pull/216 and there is already a fix https://github.com/AppDevNext/AndroidChart/pull/216/commits/be47f3663369eec5b48911d512cb6e30fb241aa5
I don't want to merge my pull request, because then I'm in the history as creator of this fix. I don't want to grab the honor of your fix, so I help you to fix, to habe the honor on your side.

### A:
To fix it, the most easy step is to cherry-pick be47f366336 to your pull request.

### B:
A more complicated way it to grab new screenshots from failing CI pipeline and replace in directory _screenshotsToCompare_ with these new artifacts

**Comment by hannesa2** [comment]
Btw, I see my screenshot pipeline don't find secret `CLASSIC_TOKEN` for pull request form a fork, that's why the screenshot diffs are not pushed to this pull request, compared to https://github.com/AppDevNext/AndroidChart/pull/216

**Comment by hannesa2** [comment]
> ### A:
> 
> To fix it, the most easy step is to cherry-pick [be47f36](https://github.com/AppDevNext/AndroidChart/commit/be47f3663369eec5b48911d512cb6e30fb241aa5) to your pull request.

I did this, because I can push to a branch of your repository

**Comment by weilanxiao** [comment]
How should I add CLASSIC_TOKEN through this check?

**Comment by hannesa2** [comment]
> How should I add CLASSIC_TOKEN through this check?

No action required. Build is green
Thank you !

**Comment by weilanxiao** [comment]
Thank you

**Comment by hannesa2** [comment]
Here you go https://github.com/AppDevNext/AndroidChart/releases/tag/3.1.0.22

**Pull request merged**
