### PR TITLE
Add RoundedBar renderer for corner radius positive/negative BarChart

### PR DESCRIPTION
**Pull request by hannesa2**
… corner radius positive/negative Bar Chart

It's https://github.com/PhilJay/MPAndroidChart/pull/5420

close https://github.com/AppDevNext/AndroidChart/issues/237

### CODE REVIEW

**Comment by hannesa2** [comment]
https://github.com/PhilJay/MPAndroidChart/pull/5420#issuecomment-2183028403
> There is crash when we use FloatArray for Y values.
> Crash happens here, as we don't have y, instead yVals
>
>  ```if ((dataSet.getEntryForIndex(j / 4).y < 0 && roundedNegativeDataSetRadius > 0)) {```
>
> This is only needed to make it perfect

Where should be this applied ? Best would be a pull request

**Comment by hannesa2** [comment]
@Paget96

https://github.com/PhilJay/MPAndroidChart/pull/5420#issuecomment-2183028403
> There is crash when we use FloatArray for Y values.
> Crash happens here, as we don't have y, instead yVals
>
>  ```if ((dataSet.getEntryForIndex(j / 4).y < 0 && roundedNegativeDataSetRadius > 0)) {```
>
> This is only needed to make it perfect

Where should be this applied ? Best would be a pull request

**Comment by hannesa2** [comment]
Screenshot differs: 1 <br/><br/>  StartTest_smokeTestStart-20-PieChartActivity.pngscreenshot <br/><br/>

**Comment by Paget96** [comment]
> @Paget96
> 
> https://github.com/PhilJay/MPAndroidChart/pull/5420#issuecomment-2183028403
> > There is crash when we use FloatArray for Y values.
> > Crash happens here, as we don't have y, instead yVals
> >
> >  ```if ((dataSet.getEntryForIndex(j / 4).y < 0 && roundedNegativeDataSetRadius > 0)) {```
> >
> > This is only needed to make it perfect
> 
> Where should be this applied ? Best would be a pull request

It's for values on the bar chart. You can find this in the renderer file.

**Comment by hannesa2** [comment]
> It's for values on the bar chart. You can find this in the renderer file.

Sure. But current line differs. Is this the "shall be" or "current is" ?
I'm confused

**Comment by hannesa2** [comment]
Screenshot differs: 2 <br/><br/>  StartTest_smokeTestStart-38-LineChartTime.pngscreenshot <br/><br/> StartTest_smokeTestStart.pngscreenshot <br/><br/>

**Comment by hannesa2** [comment]
Screenshot differs: 1 <br/><br/>  StartTest_smokeTestStart-38-LineChartTime.pngscreenshot <br/><br/>

**Comment by hannesa2** [comment]
Screenshot differs: 1 <br/><br/>  StartTest_smokeTestStart-38-LineChartTime.pngscreenshot <br/><br/>

**Comment by hannesa2** [comment]
This is the new test 
image

**Pull request merged**
